//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Web_1_Semana08.ReferenciaWCFNegocios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WCFNegocios")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcliente {
            get {
                return this.idclienteField;
            }
            set {
                if ((object.ReferenceEquals(this.idclienteField, value) != true)) {
                    this.idclienteField = value;
                    this.RaisePropertyChanged("idcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrecia {
            get {
                return this.nombreciaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreciaField, value) != true)) {
                    this.nombreciaField = value;
                    this.RaisePropertyChanged("nombrecia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/WCFNegocios")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ciudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechapedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idpedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                if ((object.ReferenceEquals(this.ciudadField, value) != true)) {
                    this.ciudadField = value;
                    this.RaisePropertyChanged("ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechapedido {
            get {
                return this.fechapedidoField;
            }
            set {
                if ((this.fechapedidoField.Equals(value) != true)) {
                    this.fechapedidoField = value;
                    this.RaisePropertyChanged("fechapedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcliente {
            get {
                return this.idclienteField;
            }
            set {
                if ((object.ReferenceEquals(this.idclienteField, value) != true)) {
                    this.idclienteField = value;
                    this.RaisePropertyChanged("idcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idpedido {
            get {
                return this.idpedidoField;
            }
            set {
                if ((this.idpedidoField.Equals(value) != true)) {
                    this.idpedidoField = value;
                    this.RaisePropertyChanged("idpedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaWCFNegocios.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/cliente", ReplyAction="http://tempuri.org/IService1/clienteResponse")]
        Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Cliente[] cliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/cliente", ReplyAction="http://tempuri.org/IService1/clienteResponse")]
        System.Threading.Tasks.Task<Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Cliente[]> clienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/pedidos", ReplyAction="http://tempuri.org/IService1/pedidosResponse")]
        Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Pedido[] pedidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/pedidos", ReplyAction="http://tempuri.org/IService1/pedidosResponse")]
        System.Threading.Tasks.Task<Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Pedido[]> pedidosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/pedido_cliente", ReplyAction="http://tempuri.org/IService1/pedido_clienteResponse")]
        Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Pedido[] pedido_cliente(string idcli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/pedido_cliente", ReplyAction="http://tempuri.org/IService1/pedido_clienteResponse")]
        System.Threading.Tasks.Task<Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Pedido[]> pedido_clienteAsync(string idcli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/pedido_anio", ReplyAction="http://tempuri.org/IService1/pedido_anioResponse")]
        Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Pedido[] pedido_anio(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/pedido_anio", ReplyAction="http://tempuri.org/IService1/pedido_anioResponse")]
        System.Threading.Tasks.Task<Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Pedido[]> pedido_anioAsync(int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Servicios_Web_1_Semana08.ReferenciaWCFNegocios.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Servicios_Web_1_Semana08.ReferenciaWCFNegocios.IService1>, Servicios_Web_1_Semana08.ReferenciaWCFNegocios.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Cliente[] cliente() {
            return base.Channel.cliente();
        }
        
        public System.Threading.Tasks.Task<Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Cliente[]> clienteAsync() {
            return base.Channel.clienteAsync();
        }
        
        public Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Pedido[] pedidos() {
            return base.Channel.pedidos();
        }
        
        public System.Threading.Tasks.Task<Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Pedido[]> pedidosAsync() {
            return base.Channel.pedidosAsync();
        }
        
        public Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Pedido[] pedido_cliente(string idcli) {
            return base.Channel.pedido_cliente(idcli);
        }
        
        public System.Threading.Tasks.Task<Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Pedido[]> pedido_clienteAsync(string idcli) {
            return base.Channel.pedido_clienteAsync(idcli);
        }
        
        public Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Pedido[] pedido_anio(int y) {
            return base.Channel.pedido_anio(y);
        }
        
        public System.Threading.Tasks.Task<Servicios_Web_1_Semana08.ReferenciaWCFNegocios.Pedido[]> pedido_anioAsync(int y) {
            return base.Channel.pedido_anioAsync(y);
        }
    }
}
